# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _meshio
else:
    import _meshio

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class PyreComponent(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.PyreComponent_swiginit(self, _meshio.new_PyreComponent())
    __swig_destroy__ = _meshio.delete_PyreComponent

    def setName(self, value):
        return _meshio.PyreComponent_setName(self, value)

    def getName(self):
        return _meshio.PyreComponent_getName(self)

    def setIdentifier(self, value):
        return _meshio.PyreComponent_setIdentifier(self, value)

    def getIdentifier(self):
        return _meshio.PyreComponent_getIdentifier(self)

# Register PyreComponent in _meshio:
_meshio.PyreComponent_swigregister(PyreComponent)
class ObserverSoln(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _meshio.delete_ObserverSoln

    def deallocate(self):
        return _meshio.ObserverSoln_deallocate(self)

    def setTimeScale(self, value):
        return _meshio.ObserverSoln_setTimeScale(self, value)

    def verifyConfiguration(self, solution):
        return _meshio.ObserverSoln_verifyConfiguration(self, solution)

    def update(self, t, tindex, solution, notification):
        return _meshio.ObserverSoln_update(self, t, tindex, solution, notification)

# Register ObserverSoln in _meshio:
_meshio.ObserverSoln_swigregister(ObserverSoln)
class ObserverPhysics(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _meshio.delete_ObserverPhysics

    def deallocate(self):
        return _meshio.ObserverPhysics_deallocate(self)

    def setPhysicsImplementation(self, physics):
        return _meshio.ObserverPhysics_setPhysicsImplementation(self, physics)

    def setTimeScale(self, value):
        return _meshio.ObserverPhysics_setTimeScale(self, value)

    def verifyConfiguration(self, solution):
        return _meshio.ObserverPhysics_verifyConfiguration(self, solution)

    def update(self, t, tindex, solution, notification):
        return _meshio.ObserverPhysics_update(self, t, tindex, solution, notification)

# Register ObserverPhysics in _meshio:
_meshio.ObserverPhysics_swigregister(ObserverPhysics)
class MeshIO(PyreComponent):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _meshio.delete_MeshIO

    def deallocate(self):
        return _meshio.MeshIO_deallocate(self)

    def read(self, mesh, check=True):
        return _meshio.MeshIO_read(self, mesh, check)

    def write(self, mesh):
        return _meshio.MeshIO_write(self, mesh)

# Register MeshIO in _meshio:
_meshio.MeshIO_swigregister(MeshIO)
class MeshIOAscii(MeshIO):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.MeshIOAscii_swiginit(self, _meshio.new_MeshIOAscii())
    __swig_destroy__ = _meshio.delete_MeshIOAscii

    def deallocate(self):
        return _meshio.MeshIOAscii_deallocate(self)

    def setFilename(self, name):
        return _meshio.MeshIOAscii_setFilename(self, name)

    def getFilename(self):
        return _meshio.MeshIOAscii_getFilename(self)

# Register MeshIOAscii in _meshio:
_meshio.MeshIOAscii_swigregister(MeshIOAscii)
class MeshIOPetsc(MeshIO):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.MeshIOPetsc_swiginit(self, _meshio.new_MeshIOPetsc())
    __swig_destroy__ = _meshio.delete_MeshIOPetsc

    def deallocate(self):
        return _meshio.MeshIOPetsc_deallocate(self)

    def setFilename(self, name):
        return _meshio.MeshIOPetsc_setFilename(self, name)

    def getFilename(self):
        return _meshio.MeshIOPetsc_getFilename(self)

    def setPrefix(self, name):
        return _meshio.MeshIOPetsc_setPrefix(self, name)

    def getPrefix(self):
        return _meshio.MeshIOPetsc_getPrefix(self)

    def setGmshMarkRecursive(self, value):
        return _meshio.MeshIOPetsc_setGmshMarkRecursive(self, value)

    def getGmshMarkRecursive(self):
        return _meshio.MeshIOPetsc_getGmshMarkRecursive(self)

# Register MeshIOPetsc in _meshio:
_meshio.MeshIOPetsc_swigregister(MeshIOPetsc)
class MeshIOCubit(MeshIO):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.MeshIOCubit_swiginit(self, _meshio.new_MeshIOCubit())
    __swig_destroy__ = _meshio.delete_MeshIOCubit

    def deallocate(self):
        return _meshio.MeshIOCubit_deallocate(self)

    def setFilename(self, name):
        return _meshio.MeshIOCubit_setFilename(self, name)

    def getFilename(self):
        return _meshio.MeshIOCubit_getFilename(self)

# Register MeshIOCubit in _meshio:
_meshio.MeshIOCubit_swigregister(MeshIOCubit)
class MeshConverter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def convert(writer, reader, checkTopology=True):
        return _meshio.MeshConverter_convert(writer, reader, checkTopology)

    def __init__(self):
        _meshio.MeshConverter_swiginit(self, _meshio.new_MeshConverter())
    __swig_destroy__ = _meshio.delete_MeshConverter

# Register MeshConverter in _meshio:
_meshio.MeshConverter_swigregister(MeshConverter)
class OutputTrigger(PyreComponent):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _meshio.delete_OutputTrigger

    def setTimeScale(self, value):
        return _meshio.OutputTrigger_setTimeScale(self, value)

    def shouldWrite(self, t, tindex):
        return _meshio.OutputTrigger_shouldWrite(self, t, tindex)

# Register OutputTrigger in _meshio:
_meshio.OutputTrigger_swigregister(OutputTrigger)
class OutputTriggerStep(OutputTrigger):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.OutputTriggerStep_swiginit(self, _meshio.new_OutputTriggerStep())
    __swig_destroy__ = _meshio.delete_OutputTriggerStep

    def shouldWrite(self, t, tindex):
        return _meshio.OutputTriggerStep_shouldWrite(self, t, tindex)

    def setNumStepsSkip(self, value):
        return _meshio.OutputTriggerStep_setNumStepsSkip(self, value)

    def getNumStepsSkip(self):
        return _meshio.OutputTriggerStep_getNumStepsSkip(self)

# Register OutputTriggerStep in _meshio:
_meshio.OutputTriggerStep_swigregister(OutputTriggerStep)
class OutputTriggerTime(OutputTrigger):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.OutputTriggerTime_swiginit(self, _meshio.new_OutputTriggerTime())
    __swig_destroy__ = _meshio.delete_OutputTriggerTime

    def shouldWrite(self, t, tindex):
        return _meshio.OutputTriggerTime_shouldWrite(self, t, tindex)

    def setTimeSkip(self, value):
        return _meshio.OutputTriggerTime_setTimeSkip(self, value)

    def getTimeSkip(self):
        return _meshio.OutputTriggerTime_getTimeSkip(self)

# Register OutputTriggerTime in _meshio:
_meshio.OutputTriggerTime_swigregister(OutputTriggerTime)
class DataWriter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _meshio.delete_DataWriter

    def clone(self):
        return _meshio.DataWriter_clone(self)

    def deallocate(self):
        return _meshio.DataWriter_deallocate(self)

    def setTimeScale(self, value):
        return _meshio.DataWriter_setTimeScale(self, value)

    def isOpen(self):
        return _meshio.DataWriter_isOpen(self)

    def open(self, mesh, isInfo):
        return _meshio.DataWriter_open(self, mesh, isInfo)

    def close(self):
        return _meshio.DataWriter_close(self)

    def openTimeStep(self, t, mesh):
        return _meshio.DataWriter_openTimeStep(self, t, mesh)

    def closeTimeStep(self):
        return _meshio.DataWriter_closeTimeStep(self)

    def writeVertexField(self, t, field):
        return _meshio.DataWriter_writeVertexField(self, t, field)

    def writeCellField(self, t, subfield):
        return _meshio.DataWriter_writeCellField(self, t, subfield)

    def writePointNames(self, names, mesh):
        return _meshio.DataWriter_writePointNames(self, names, mesh)

# Register DataWriter in _meshio:
_meshio.DataWriter_swigregister(DataWriter)
class DataWriterVTK(DataWriter):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.DataWriterVTK_swiginit(self, _meshio.new_DataWriterVTK())
    __swig_destroy__ = _meshio.delete_DataWriterVTK

    def clone(self):
        return _meshio.DataWriterVTK_clone(self)

    def deallocate(self):
        return _meshio.DataWriterVTK_deallocate(self)

    def filename(self, filename):
        return _meshio.DataWriterVTK_filename(self, filename)

    def timeFormat(self, format):
        return _meshio.DataWriterVTK_timeFormat(self, format)

    def timeConstant(self, value):
        return _meshio.DataWriterVTK_timeConstant(self, value)

    def precision(self, value):
        return _meshio.DataWriterVTK_precision(self, value)

    def open(self, mesh, isInfo):
        return _meshio.DataWriterVTK_open(self, mesh, isInfo)

    def close(self):
        return _meshio.DataWriterVTK_close(self)

    def openTimeStep(self, t, mesh):
        return _meshio.DataWriterVTK_openTimeStep(self, t, mesh)

    def closeTimeStep(self):
        return _meshio.DataWriterVTK_closeTimeStep(self)

    def writeVertexField(self, t, field):
        return _meshio.DataWriterVTK_writeVertexField(self, t, field)

    def writeCellField(self, t, subfield):
        return _meshio.DataWriterVTK_writeCellField(self, t, subfield)

# Register DataWriterVTK in _meshio:
_meshio.DataWriterVTK_swigregister(DataWriterVTK)
class DataWriterHDF5(DataWriter):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.DataWriterHDF5_swiginit(self, _meshio.new_DataWriterHDF5())
    __swig_destroy__ = _meshio.delete_DataWriterHDF5

    def clone(self):
        return _meshio.DataWriterHDF5_clone(self)

    def deallocate(self):
        return _meshio.DataWriterHDF5_deallocate(self)

    def filename(self, filename):
        return _meshio.DataWriterHDF5_filename(self, filename)

    def hdf5Filename(self):
        return _meshio.DataWriterHDF5_hdf5Filename(self)

    def open(self, mesh, isInfo):
        return _meshio.DataWriterHDF5_open(self, mesh, isInfo)

    def close(self):
        return _meshio.DataWriterHDF5_close(self)

    def writeVertexField(self, t, field):
        return _meshio.DataWriterHDF5_writeVertexField(self, t, field)

    def writeCellField(self, t, subfield):
        return _meshio.DataWriterHDF5_writeCellField(self, t, subfield)

    def writePointNames(self, names, mesh):
        return _meshio.DataWriterHDF5_writePointNames(self, names, mesh)

# Register DataWriterHDF5 in _meshio:
_meshio.DataWriterHDF5_swigregister(DataWriterHDF5)
class DataWriterHDF5Ext(DataWriter):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.DataWriterHDF5Ext_swiginit(self, _meshio.new_DataWriterHDF5Ext())
    __swig_destroy__ = _meshio.delete_DataWriterHDF5Ext

    def clone(self):
        return _meshio.DataWriterHDF5Ext_clone(self)

    def deallocate(self):
        return _meshio.DataWriterHDF5Ext_deallocate(self)

    def filename(self, filename):
        return _meshio.DataWriterHDF5Ext_filename(self, filename)

    def hdf5Filename(self):
        return _meshio.DataWriterHDF5Ext_hdf5Filename(self)

    def open(self, mesh, isInfo):
        return _meshio.DataWriterHDF5Ext_open(self, mesh, isInfo)

    def close(self):
        return _meshio.DataWriterHDF5Ext_close(self)

    def writeVertexField(self, t, field):
        return _meshio.DataWriterHDF5Ext_writeVertexField(self, t, field)

    def writeCellField(self, t, subfield):
        return _meshio.DataWriterHDF5Ext_writeCellField(self, t, subfield)

    def writePointNames(self, names, mesh):
        return _meshio.DataWriterHDF5Ext_writePointNames(self, names, mesh)

# Register DataWriterHDF5Ext in _meshio:
_meshio.DataWriterHDF5Ext_swigregister(DataWriterHDF5Ext)
class OutputObserver(PyreComponent):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.OutputObserver_swiginit(self, _meshio.new_OutputObserver())
    __swig_destroy__ = _meshio.delete_OutputObserver

    def deallocate(self):
        return _meshio.OutputObserver_deallocate(self)

    def setTrigger(self, trigger):
        return _meshio.OutputObserver_setTrigger(self, trigger)

    def getTrigger(self):
        return _meshio.OutputObserver_getTrigger(self)

    def setWriter(self, writer):
        return _meshio.OutputObserver_setWriter(self, writer)

    def setOutputBasisOrder(self, value):
        return _meshio.OutputObserver_setOutputBasisOrder(self, value)

    def setRefineLevels(self, value):
        return _meshio.OutputObserver_setRefineLevels(self, value)

    def setTimeScale(self, value):
        return _meshio.OutputObserver_setTimeScale(self, value)

# Register OutputObserver in _meshio:
_meshio.OutputObserver_swigregister(OutputObserver)
class OutputSoln(ObserverSoln, OutputObserver):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.OutputSoln_swiginit(self, _meshio.new_OutputSoln())
    __swig_destroy__ = _meshio.delete_OutputSoln

    def deallocate(self):
        return _meshio.OutputSoln_deallocate(self)

    def setOutputSubfields(self, names):
        return _meshio.OutputSoln_setOutputSubfields(self, names)

    def getOutputSubfields(self):
        return _meshio.OutputSoln_getOutputSubfields(self)

    def setTimeScale(self, value):
        return _meshio.OutputSoln_setTimeScale(self, value)

    def verifyConfiguration(self, solution):
        return _meshio.OutputSoln_verifyConfiguration(self, solution)

    def update(self, t, tindex, solution, notification):
        return _meshio.OutputSoln_update(self, t, tindex, solution, notification)

# Register OutputSoln in _meshio:
_meshio.OutputSoln_swigregister(OutputSoln)
class OutputSolnDomain(OutputSoln):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.OutputSolnDomain_swiginit(self, _meshio.new_OutputSolnDomain())
    __swig_destroy__ = _meshio.delete_OutputSolnDomain

# Register OutputSolnDomain in _meshio:
_meshio.OutputSolnDomain_swigregister(OutputSolnDomain)
class OutputSolnBoundary(OutputSoln):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.OutputSolnBoundary_swiginit(self, _meshio.new_OutputSolnBoundary())
    __swig_destroy__ = _meshio.delete_OutputSolnBoundary

    def setLabelName(self, value):
        return _meshio.OutputSolnBoundary_setLabelName(self, value)

    def setLabelValue(self, value):
        return _meshio.OutputSolnBoundary_setLabelValue(self, value)

    def verifyConfiguration(self, solution):
        return _meshio.OutputSolnBoundary_verifyConfiguration(self, solution)

# Register OutputSolnBoundary in _meshio:
_meshio.OutputSolnBoundary_swigregister(OutputSolnBoundary)
class OutputSolnPoints(OutputSoln):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.OutputSolnPoints_swiginit(self, _meshio.new_OutputSolnPoints())
    __swig_destroy__ = _meshio.delete_OutputSolnPoints

    def setPoints(self, pointCoords, pointNames):
        return _meshio.OutputSolnPoints_setPoints(self, pointCoords, pointNames)

# Register OutputSolnPoints in _meshio:
_meshio.OutputSolnPoints_swigregister(OutputSolnPoints)
class OutputPhysics(ObserverPhysics, OutputObserver):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _meshio.OutputPhysics_swiginit(self, _meshio.new_OutputPhysics())
    __swig_destroy__ = _meshio.delete_OutputPhysics

    def deallocate(self):
        return _meshio.OutputPhysics_deallocate(self)

    def setInfoFields(self, names):
        return _meshio.OutputPhysics_setInfoFields(self, names)

    def getInfoFields(self):
        return _meshio.OutputPhysics_getInfoFields(self)

    def setDataFields(self, names):
        return _meshio.OutputPhysics_setDataFields(self, names)

    def getDataFields(self):
        return _meshio.OutputPhysics_getDataFields(self)

    def setTimeScale(self, value):
        return _meshio.OutputPhysics_setTimeScale(self, value)

    def verifyConfiguration(self, solution):
        return _meshio.OutputPhysics_verifyConfiguration(self, solution)

    def update(self, t, tindex, solution, notification):
        return _meshio.OutputPhysics_update(self, t, tindex, solution, notification)

# Register OutputPhysics in _meshio:
_meshio.OutputPhysics_swigregister(OutputPhysics)

