# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _materials
else:
    import _materials

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class PyreComponent(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.PyreComponent_swiginit(self, _materials.new_PyreComponent())
    __swig_destroy__ = _materials.delete_PyreComponent

    def setName(self, value):
        return _materials.PyreComponent_setName(self, value)

    def getName(self):
        return _materials.PyreComponent_getName(self)

    def setIdentifier(self, value):
        return _materials.PyreComponent_setIdentifier(self, value)

    def getIdentifier(self):
        return _materials.PyreComponent_getIdentifier(self)

# Register PyreComponent in _materials:
_materials.PyreComponent_swigregister(PyreComponent)
class Physics(PyreComponent):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    QUASISTATIC = _materials.Physics_QUASISTATIC
    DYNAMIC = _materials.Physics_DYNAMIC
    DYNAMIC_IMEX = _materials.Physics_DYNAMIC_IMEX
    __swig_destroy__ = _materials.delete_Physics

    def deallocate(self):
        return _materials.Physics_deallocate(self)

    def setLabelName(self, value):
        return _materials.Physics_setLabelName(self, value)

    def getLabelName(self):
        return _materials.Physics_getLabelName(self)

    def setLabelValue(self, value):
        return _materials.Physics_setLabelValue(self, value)

    def getLabelValue(self):
        return _materials.Physics_getLabelValue(self)

    def setScales(self, dim):
        return _materials.Physics_setScales(self, dim)

    def getScales(self):
        return _materials.Physics_getScales(self)

    def setFormulation(self, value):
        return _materials.Physics_setFormulation(self, value)

    def setAuxiliaryFieldDB(self, value):
        return _materials.Physics_setAuxiliaryFieldDB(self, value)

    def setAuxiliarySubfieldDiscretization(self, subfieldName, basisOrder, quadOrder, dimension, cellBasis, feSpace, isBasisContinuous):
        return _materials.Physics_setAuxiliarySubfieldDiscretization(self, subfieldName, basisOrder, quadOrder, dimension, cellBasis, feSpace, isBasisContinuous)

    def setDerivedSubfieldDiscretization(self, subfieldName, basisOrder, quadOrder, dimension, cellBasis, feSpace, isBasisContinuous):
        return _materials.Physics_setDerivedSubfieldDiscretization(self, subfieldName, basisOrder, quadOrder, dimension, cellBasis, feSpace, isBasisContinuous)

    def registerObserver(self, observer):
        return _materials.Physics_registerObserver(self, observer)

    def removeObserver(self, observer):
        return _materials.Physics_removeObserver(self, observer)

    def getObservers(self):
        return _materials.Physics_getObservers(self)

    def getKernelConstants(self, dt):
        return _materials.Physics_getKernelConstants(self, dt)

    def verifyConfiguration(self, solution):
        return _materials.Physics_verifyConfiguration(self, solution)

    def createIntegrator(self, solution):
        return _materials.Physics_createIntegrator(self, solution)

    def createConstraints(self, solution):
        return _materials.Physics_createConstraints(self, solution)

    def createAuxiliaryField(self, solution, physicsMesh):
        return _materials.Physics_createAuxiliaryField(self, solution, physicsMesh)

    def createDiagnosticField(self, solution, physicsMesh):
        return _materials.Physics_createDiagnosticField(self, solution, physicsMesh)

    def createDerivedField(self, solution, physicsMesh):
        return _materials.Physics_createDerivedField(self, solution, physicsMesh)

    def updateAuxiliaryField(self, auxiliaryField, t):
        return _materials.Physics_updateAuxiliaryField(self, auxiliaryField, t)

# Register Physics in _materials:
_materials.Physics_swigregister(Physics)
class Material(Physics):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _materials.delete_Material

    def deallocate(self):
        return _materials.Material_deallocate(self)

    def setGravityField(self, g):
        return _materials.Material_setGravityField(self, g)

    def createConstraints(self, solution):
        return _materials.Material_createConstraints(self, solution)

    def getSolverDefaults(self, isParallel, hasFault):
        return _materials.Material_getSolverDefaults(self, isParallel, hasFault)

# Register Material in _materials:
_materials.Material_swigregister(Material)
class Elasticity(Material):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.Elasticity_swiginit(self, _materials.new_Elasticity())
    __swig_destroy__ = _materials.delete_Elasticity

    def deallocate(self):
        return _materials.Elasticity_deallocate(self)

    def useBodyForce(self, *args):
        return _materials.Elasticity_useBodyForce(self, *args)

    def setBulkRheology(self, rheology):
        return _materials.Elasticity_setBulkRheology(self, rheology)

    def getBulkRheology(self):
        return _materials.Elasticity_getBulkRheology(self)

    def verifyConfiguration(self, solution):
        return _materials.Elasticity_verifyConfiguration(self, solution)

    def createIntegrator(self, solution):
        return _materials.Elasticity_createIntegrator(self, solution)

    def createAuxiliaryField(self, solution, domainMesh):
        return _materials.Elasticity_createAuxiliaryField(self, solution, domainMesh)

    def createDerivedField(self, solution, domainMesh):
        return _materials.Elasticity_createDerivedField(self, solution, domainMesh)

    def getSolverDefaults(self, isParallel, hasFault):
        return _materials.Elasticity_getSolverDefaults(self, isParallel, hasFault)

# Register Elasticity in _materials:
_materials.Elasticity_swigregister(Elasticity)
class RheologyElasticity(PyreComponent):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _materials.delete_RheologyElasticity

    def deallocate(self):
        return _materials.RheologyElasticity_deallocate(self)

    def getAuxiliaryFactory(self):
        return _materials.RheologyElasticity_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.RheologyElasticity_addAuxiliarySubfields(self)

    def getKernelf1v(self, coordsys):
        return _materials.RheologyElasticity_getKernelf1v(self, coordsys)

    def getKernelJf3vu(self, coordsys):
        return _materials.RheologyElasticity_getKernelJf3vu(self, coordsys)

    def getKernelf0Neg(self, coordsys):
        return _materials.RheologyElasticity_getKernelf0Neg(self, coordsys)

    def getKernelf0Pos(self, coordsys):
        return _materials.RheologyElasticity_getKernelf0Pos(self, coordsys)

    def getKernelCauchyStressVector(self, coordsys):
        return _materials.RheologyElasticity_getKernelCauchyStressVector(self, coordsys)

    def addKernelsUpdateStateVars(self, kernels, coordsys):
        return _materials.RheologyElasticity_addKernelsUpdateStateVars(self, kernels, coordsys)

    def updateKernelConstants(self, kernelConstants, dt):
        return _materials.RheologyElasticity_updateKernelConstants(self, kernelConstants, dt)

# Register RheologyElasticity in _materials:
_materials.RheologyElasticity_swigregister(RheologyElasticity)
class IsotropicLinearElasticity(RheologyElasticity):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.IsotropicLinearElasticity_swiginit(self, _materials.new_IsotropicLinearElasticity())
    __swig_destroy__ = _materials.delete_IsotropicLinearElasticity

    def deallocate(self):
        return _materials.IsotropicLinearElasticity_deallocate(self)

    def useReferenceState(self, *args):
        return _materials.IsotropicLinearElasticity_useReferenceState(self, *args)

    def getAuxiliaryFactory(self):
        return _materials.IsotropicLinearElasticity_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.IsotropicLinearElasticity_addAuxiliarySubfields(self)

    def getKernelf1v(self, coordsys):
        return _materials.IsotropicLinearElasticity_getKernelf1v(self, coordsys)

    def getKernelJf3vu(self, coordsys):
        return _materials.IsotropicLinearElasticity_getKernelJf3vu(self, coordsys)

    def getKernelf0Neg(self, coordsys):
        return _materials.IsotropicLinearElasticity_getKernelf0Neg(self, coordsys)

    def getKernelf0Pos(self, coordsys):
        return _materials.IsotropicLinearElasticity_getKernelf0Pos(self, coordsys)

    def getKernelCauchyStressVector(self, coordsys):
        return _materials.IsotropicLinearElasticity_getKernelCauchyStressVector(self, coordsys)

# Register IsotropicLinearElasticity in _materials:
_materials.IsotropicLinearElasticity_swigregister(IsotropicLinearElasticity)
class IsotropicLinearMaxwell(RheologyElasticity):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.IsotropicLinearMaxwell_swiginit(self, _materials.new_IsotropicLinearMaxwell())
    __swig_destroy__ = _materials.delete_IsotropicLinearMaxwell

    def deallocate(self):
        return _materials.IsotropicLinearMaxwell_deallocate(self)

    def useReferenceState(self, *args):
        return _materials.IsotropicLinearMaxwell_useReferenceState(self, *args)

    def getAuxiliaryFactory(self):
        return _materials.IsotropicLinearMaxwell_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.IsotropicLinearMaxwell_addAuxiliarySubfields(self)

    def getKernelf1v(self, coordsys):
        return _materials.IsotropicLinearMaxwell_getKernelf1v(self, coordsys)

    def getKernelJf3vu(self, coordsys):
        return _materials.IsotropicLinearMaxwell_getKernelJf3vu(self, coordsys)

    def getKernelf0Neg(self, coordsys):
        return _materials.IsotropicLinearMaxwell_getKernelf0Neg(self, coordsys)

    def getKernelf0Pos(self, coordsys):
        return _materials.IsotropicLinearMaxwell_getKernelf0Pos(self, coordsys)

    def getKernelCauchyStressVector(self, coordsys):
        return _materials.IsotropicLinearMaxwell_getKernelCauchyStressVector(self, coordsys)

    def addKernelsUpdateStateVars(self, kernels, coordsys):
        return _materials.IsotropicLinearMaxwell_addKernelsUpdateStateVars(self, kernels, coordsys)

    def updateKernelConstants(self, kernelConstants, dt):
        return _materials.IsotropicLinearMaxwell_updateKernelConstants(self, kernelConstants, dt)

# Register IsotropicLinearMaxwell in _materials:
_materials.IsotropicLinearMaxwell_swigregister(IsotropicLinearMaxwell)
class IsotropicLinearGenMaxwell(RheologyElasticity):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.IsotropicLinearGenMaxwell_swiginit(self, _materials.new_IsotropicLinearGenMaxwell())
    __swig_destroy__ = _materials.delete_IsotropicLinearGenMaxwell

    def deallocate(self):
        return _materials.IsotropicLinearGenMaxwell_deallocate(self)

    def useReferenceState(self, *args):
        return _materials.IsotropicLinearGenMaxwell_useReferenceState(self, *args)

    def getAuxiliaryFactory(self):
        return _materials.IsotropicLinearGenMaxwell_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.IsotropicLinearGenMaxwell_addAuxiliarySubfields(self)

    def getKernelf1v(self, coordsys):
        return _materials.IsotropicLinearGenMaxwell_getKernelf1v(self, coordsys)

    def getKernelJf3vu(self, coordsys):
        return _materials.IsotropicLinearGenMaxwell_getKernelJf3vu(self, coordsys)

    def getKernelf0Neg(self, coordsys):
        return _materials.IsotropicLinearGenMaxwell_getKernelf0Neg(self, coordsys)

    def getKernelf0Pos(self, coordsys):
        return _materials.IsotropicLinearGenMaxwell_getKernelf0Pos(self, coordsys)

    def getKernelCauchyStressVector(self, coordsys):
        return _materials.IsotropicLinearGenMaxwell_getKernelCauchyStressVector(self, coordsys)

    def addKernelsUpdateStateVars(self, kernels, coordsys):
        return _materials.IsotropicLinearGenMaxwell_addKernelsUpdateStateVars(self, kernels, coordsys)

    def updateKernelConstants(self, kernelConstants, dt):
        return _materials.IsotropicLinearGenMaxwell_updateKernelConstants(self, kernelConstants, dt)

# Register IsotropicLinearGenMaxwell in _materials:
_materials.IsotropicLinearGenMaxwell_swigregister(IsotropicLinearGenMaxwell)
class IsotropicPowerLaw(RheologyElasticity):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.IsotropicPowerLaw_swiginit(self, _materials.new_IsotropicPowerLaw())
    __swig_destroy__ = _materials.delete_IsotropicPowerLaw

    def deallocate(self):
        return _materials.IsotropicPowerLaw_deallocate(self)

    def useReferenceState(self, *args):
        return _materials.IsotropicPowerLaw_useReferenceState(self, *args)

    def getAuxiliaryFactory(self):
        return _materials.IsotropicPowerLaw_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.IsotropicPowerLaw_addAuxiliarySubfields(self)

    def getKernelf1v(self, coordsys):
        return _materials.IsotropicPowerLaw_getKernelf1v(self, coordsys)

    def getKernelJf3vu(self, coordsys):
        return _materials.IsotropicPowerLaw_getKernelJf3vu(self, coordsys)

    def getKernelf0Neg(self, coordsys):
        return _materials.IsotropicPowerLaw_getKernelf0Neg(self, coordsys)

    def getKernelf0Pos(self, coordsys):
        return _materials.IsotropicPowerLaw_getKernelf0Pos(self, coordsys)

    def getKernelCauchyStressVector(self, coordsys):
        return _materials.IsotropicPowerLaw_getKernelCauchyStressVector(self, coordsys)

    def addKernelsUpdateStateVars(self, kernels, coordsys):
        return _materials.IsotropicPowerLaw_addKernelsUpdateStateVars(self, kernels, coordsys)

    def updateKernelConstants(self, kernelConstants, dt):
        return _materials.IsotropicPowerLaw_updateKernelConstants(self, kernelConstants, dt)

# Register IsotropicPowerLaw in _materials:
_materials.IsotropicPowerLaw_swigregister(IsotropicPowerLaw)
class IncompressibleElasticity(Material):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.IncompressibleElasticity_swiginit(self, _materials.new_IncompressibleElasticity())
    __swig_destroy__ = _materials.delete_IncompressibleElasticity

    def deallocate(self):
        return _materials.IncompressibleElasticity_deallocate(self)

    def useBodyForce(self, *args):
        return _materials.IncompressibleElasticity_useBodyForce(self, *args)

    def setBulkRheology(self, rheology):
        return _materials.IncompressibleElasticity_setBulkRheology(self, rheology)

    def getBulkRheology(self):
        return _materials.IncompressibleElasticity_getBulkRheology(self)

    def verifyConfiguration(self, solution):
        return _materials.IncompressibleElasticity_verifyConfiguration(self, solution)

    def createIntegrator(self, solution):
        return _materials.IncompressibleElasticity_createIntegrator(self, solution)

    def createAuxiliaryField(self, solution, domainMesh):
        return _materials.IncompressibleElasticity_createAuxiliaryField(self, solution, domainMesh)

    def createDerivedField(self, solution, domainMesh):
        return _materials.IncompressibleElasticity_createDerivedField(self, solution, domainMesh)

    def getSolverDefaults(self, isParallel, hasFault):
        return _materials.IncompressibleElasticity_getSolverDefaults(self, isParallel, hasFault)

# Register IncompressibleElasticity in _materials:
_materials.IncompressibleElasticity_swigregister(IncompressibleElasticity)
class RheologyIncompressibleElasticity(PyreComponent):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _materials.delete_RheologyIncompressibleElasticity

    def deallocate(self):
        return _materials.RheologyIncompressibleElasticity_deallocate(self)

    def getAuxiliaryFactory(self):
        return _materials.RheologyIncompressibleElasticity_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.RheologyIncompressibleElasticity_addAuxiliarySubfields(self)

    def getKernelf0p(self, coordsys):
        return _materials.RheologyIncompressibleElasticity_getKernelf0p(self, coordsys)

    def getKernelf1u(self, coordsys):
        return _materials.RheologyIncompressibleElasticity_getKernelf1u(self, coordsys)

    def getKernelJf0pp(self, coordsys):
        return _materials.RheologyIncompressibleElasticity_getKernelJf0pp(self, coordsys)

    def getKernelJf3uu(self, coordsys):
        return _materials.RheologyIncompressibleElasticity_getKernelJf3uu(self, coordsys)

    def getKernelCauchyStressVector(self, coordsys):
        return _materials.RheologyIncompressibleElasticity_getKernelCauchyStressVector(self, coordsys)

    def addKernelsUpdateStateVars(self, kernels, coordsys):
        return _materials.RheologyIncompressibleElasticity_addKernelsUpdateStateVars(self, kernels, coordsys)

    def updateKernelConstants(self, kernelConstants, dt):
        return _materials.RheologyIncompressibleElasticity_updateKernelConstants(self, kernelConstants, dt)

# Register RheologyIncompressibleElasticity in _materials:
_materials.RheologyIncompressibleElasticity_swigregister(RheologyIncompressibleElasticity)
class IsotropicLinearIncompElasticity(RheologyIncompressibleElasticity):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.IsotropicLinearIncompElasticity_swiginit(self, _materials.new_IsotropicLinearIncompElasticity())
    __swig_destroy__ = _materials.delete_IsotropicLinearIncompElasticity

    def deallocate(self):
        return _materials.IsotropicLinearIncompElasticity_deallocate(self)

    def useReferenceState(self, *args):
        return _materials.IsotropicLinearIncompElasticity_useReferenceState(self, *args)

    def getAuxiliaryFactory(self):
        return _materials.IsotropicLinearIncompElasticity_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.IsotropicLinearIncompElasticity_addAuxiliarySubfields(self)

    def getKernelf0p(self, coordsys):
        return _materials.IsotropicLinearIncompElasticity_getKernelf0p(self, coordsys)

    def getKernelf1u(self, coordsys):
        return _materials.IsotropicLinearIncompElasticity_getKernelf1u(self, coordsys)

    def getKernelJf0pp(self, coordsys):
        return _materials.IsotropicLinearIncompElasticity_getKernelJf0pp(self, coordsys)

    def getKernelJf3uu(self, coordsys):
        return _materials.IsotropicLinearIncompElasticity_getKernelJf3uu(self, coordsys)

    def getKernelCauchyStressVector(self, coordsys):
        return _materials.IsotropicLinearIncompElasticity_getKernelCauchyStressVector(self, coordsys)

# Register IsotropicLinearIncompElasticity in _materials:
_materials.IsotropicLinearIncompElasticity_swigregister(IsotropicLinearIncompElasticity)
class Poroelasticity(Material):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.Poroelasticity_swiginit(self, _materials.new_Poroelasticity())
    __swig_destroy__ = _materials.delete_Poroelasticity

    def deallocate(self):
        return _materials.Poroelasticity_deallocate(self)

    def useBodyForce(self, *args):
        return _materials.Poroelasticity_useBodyForce(self, *args)

    def useSourceDensity(self, *args):
        return _materials.Poroelasticity_useSourceDensity(self, *args)

    def useStateVars(self, *args):
        return _materials.Poroelasticity_useStateVars(self, *args)

    def setBulkRheology(self, rheology):
        return _materials.Poroelasticity_setBulkRheology(self, rheology)

    def getBulkRheology(self):
        return _materials.Poroelasticity_getBulkRheology(self)

    def verifyConfiguration(self, solution):
        return _materials.Poroelasticity_verifyConfiguration(self, solution)

    def createIntegrator(self, solution):
        return _materials.Poroelasticity_createIntegrator(self, solution)

    def createAuxiliaryField(self, solution, domainMesh):
        return _materials.Poroelasticity_createAuxiliaryField(self, solution, domainMesh)

    def createDerivedField(self, solution, domainMesh):
        return _materials.Poroelasticity_createDerivedField(self, solution, domainMesh)

    def getSolverDefaults(self, isParallel, hasFault):
        return _materials.Poroelasticity_getSolverDefaults(self, isParallel, hasFault)

# Register Poroelasticity in _materials:
_materials.Poroelasticity_swigregister(Poroelasticity)
class RheologyPoroelasticity(PyreComponent):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _materials.delete_RheologyPoroelasticity

    def deallocate(self):
        return _materials.RheologyPoroelasticity_deallocate(self)

    def getAuxiliaryFactory(self):
        return _materials.RheologyPoroelasticity_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.RheologyPoroelasticity_addAuxiliarySubfields(self)

    def getKernelg0p(self, coordsys, _useBodyForce, _gravityField, _useSourceDensity):
        return _materials.RheologyPoroelasticity_getKernelg0p(self, coordsys, _useBodyForce, _gravityField, _useSourceDensity)

    def getKernelg1p_explicit(self, coordsys, _gravityField):
        return _materials.RheologyPoroelasticity_getKernelg1p_explicit(self, coordsys, _gravityField)

    def getKernelf0p_explicit(self, coordsys):
        return _materials.RheologyPoroelasticity_getKernelf0p_explicit(self, coordsys)

    def getKernelf0p_implicit(self, coordsys, _useBodyForce, _gravityField, _useSourceDensity):
        return _materials.RheologyPoroelasticity_getKernelf0p_implicit(self, coordsys, _useBodyForce, _gravityField, _useSourceDensity)

    def getKernelf1p_implicit(self, coordsys, _useBodyForce, _gravityField):
        return _materials.RheologyPoroelasticity_getKernelf1p_implicit(self, coordsys, _useBodyForce, _gravityField)

    def getKernelJf3uu(self, coordsys):
        return _materials.RheologyPoroelasticity_getKernelJf3uu(self, coordsys)

    def getKernelJf2up(self, coordsys):
        return _materials.RheologyPoroelasticity_getKernelJf2up(self, coordsys)

    def getKernelJf2ue(self, coordsys):
        return _materials.RheologyPoroelasticity_getKernelJf2ue(self, coordsys)

    def getKernelJf0pp(self, coordsys):
        return _materials.RheologyPoroelasticity_getKernelJf0pp(self, coordsys)

    def getKernelJf3pp(self, coordsys):
        return _materials.RheologyPoroelasticity_getKernelJf3pp(self, coordsys)

    def getKernelJf0pe(self, coordsys):
        return _materials.RheologyPoroelasticity_getKernelJf0pe(self, coordsys)

    def getKernelCauchyStressVector(self, coordsys):
        return _materials.RheologyPoroelasticity_getKernelCauchyStressVector(self, coordsys)

    def addKernelsUpdateStateVarsImplicit(self, kernels, coordsys, _useStateVars):
        return _materials.RheologyPoroelasticity_addKernelsUpdateStateVarsImplicit(self, kernels, coordsys, _useStateVars)

    def updateKernelConstants(self, kernelConstants, dt):
        return _materials.RheologyPoroelasticity_updateKernelConstants(self, kernelConstants, dt)

# Register RheologyPoroelasticity in _materials:
_materials.RheologyPoroelasticity_swigregister(RheologyPoroelasticity)
class IsotropicLinearPoroelasticity(RheologyPoroelasticity):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.IsotropicLinearPoroelasticity_swiginit(self, _materials.new_IsotropicLinearPoroelasticity())
    __swig_destroy__ = _materials.delete_IsotropicLinearPoroelasticity

    def deallocate(self):
        return _materials.IsotropicLinearPoroelasticity_deallocate(self)

    def useReferenceState(self, *args):
        return _materials.IsotropicLinearPoroelasticity_useReferenceState(self, *args)

    def useTensorPermeability(self, *args):
        return _materials.IsotropicLinearPoroelasticity_useTensorPermeability(self, *args)

    def getAuxiliaryFactory(self):
        return _materials.IsotropicLinearPoroelasticity_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.IsotropicLinearPoroelasticity_addAuxiliarySubfields(self)

    def getKernelg0p(self, coordsys, _useBodyForce, _gravityField, _useSourceDensity):
        return _materials.IsotropicLinearPoroelasticity_getKernelg0p(self, coordsys, _useBodyForce, _gravityField, _useSourceDensity)

    def getKernelg1p_explicit(self, coordsys, _gravityField):
        return _materials.IsotropicLinearPoroelasticity_getKernelg1p_explicit(self, coordsys, _gravityField)

    def getKernelg1v_explicit(self, coordsys):
        return _materials.IsotropicLinearPoroelasticity_getKernelg1v_explicit(self, coordsys)

    def getKernelf0p_explicit(self, coordsys):
        return _materials.IsotropicLinearPoroelasticity_getKernelf0p_explicit(self, coordsys)

    def getKernelf0p_implicit(self, coordsys, _useBodyForce, _gravityField, _useSourceDensity):
        return _materials.IsotropicLinearPoroelasticity_getKernelf0p_implicit(self, coordsys, _useBodyForce, _gravityField, _useSourceDensity)

    def getKernelf1u_implicit(self, coordsys):
        return _materials.IsotropicLinearPoroelasticity_getKernelf1u_implicit(self, coordsys)

    def getKernelf1p_implicit(self, coordsys, _useBodyForce, _gravityField):
        return _materials.IsotropicLinearPoroelasticity_getKernelf1p_implicit(self, coordsys, _useBodyForce, _gravityField)

    def getKernelJf3uu(self, coordsys):
        return _materials.IsotropicLinearPoroelasticity_getKernelJf3uu(self, coordsys)

    def getKernelJf2up(self, coordsys):
        return _materials.IsotropicLinearPoroelasticity_getKernelJf2up(self, coordsys)

    def getKernelJf2ue(self, coordsys):
        return _materials.IsotropicLinearPoroelasticity_getKernelJf2ue(self, coordsys)

    def getKernelJf0pp(self, coordsys):
        return _materials.IsotropicLinearPoroelasticity_getKernelJf0pp(self, coordsys)

    def getKernelJf3pp(self, coordsys):
        return _materials.IsotropicLinearPoroelasticity_getKernelJf3pp(self, coordsys)

    def getKernelJf0pe(self, coordsys):
        return _materials.IsotropicLinearPoroelasticity_getKernelJf0pe(self, coordsys)

    def getKernelCauchyStressVector(self, coordsys):
        return _materials.IsotropicLinearPoroelasticity_getKernelCauchyStressVector(self, coordsys)

    def updateKernelConstants(self, kernelConstants, dt):
        return _materials.IsotropicLinearPoroelasticity_updateKernelConstants(self, kernelConstants, dt)

    def addKernelsUpdateStateVarsImplicit(self, kernels, coordsys, _useStateVars):
        return _materials.IsotropicLinearPoroelasticity_addKernelsUpdateStateVarsImplicit(self, kernels, coordsys, _useStateVars)

    def addKernelsUpdateStateVarsExplicit(self, kernels, coordsys, _useStateVars):
        return _materials.IsotropicLinearPoroelasticity_addKernelsUpdateStateVarsExplicit(self, kernels, coordsys, _useStateVars)

# Register IsotropicLinearPoroelasticity in _materials:
_materials.IsotropicLinearPoroelasticity_swigregister(IsotropicLinearPoroelasticity)
class Heat(Material):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.Heat_swiginit(self, _materials.new_Heat())
    __swig_destroy__ = _materials.delete_Heat

    def deallocate(self):
        return _materials.Heat_deallocate(self)

    def useHeatSource(self, *args):
        return _materials.Heat_useHeatSource(self, *args)

    def setBulkRheology(self, rheology):
        return _materials.Heat_setBulkRheology(self, rheology)

    def getBulkRheology(self):
        return _materials.Heat_getBulkRheology(self)

    def verifyConfiguration(self, solution):
        return _materials.Heat_verifyConfiguration(self, solution)

    def createIntegrator(self, solution):
        return _materials.Heat_createIntegrator(self, solution)

    def createAuxiliaryField(self, solution, domainMesh):
        return _materials.Heat_createAuxiliaryField(self, solution, domainMesh)

    def createDerivedField(self, solution, domainMesh):
        return _materials.Heat_createDerivedField(self, solution, domainMesh)

    def getSolverDefaults(self, isParallel, hasFault):
        return _materials.Heat_getSolverDefaults(self, isParallel, hasFault)

# Register Heat in _materials:
_materials.Heat_swigregister(Heat)
class RheologyHeat(PyreComponent):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _materials.delete_RheologyHeat

    def deallocate(self):
        return _materials.RheologyHeat_deallocate(self)

    def getAuxiliaryFactory(self):
        return _materials.RheologyHeat_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.RheologyHeat_addAuxiliarySubfields(self)

    def updateKernelConstants(self, kernelConstants, dt):
        return _materials.RheologyHeat_updateKernelConstants(self, kernelConstants, dt)

# Register RheologyHeat in _materials:
_materials.RheologyHeat_swigregister(RheologyHeat)
class IsotropicHeat(RheologyHeat):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.IsotropicHeat_swiginit(self, _materials.new_IsotropicHeat())
    __swig_destroy__ = _materials.delete_IsotropicHeat

    def deallocate(self):
        return _materials.IsotropicHeat_deallocate(self)

    def getAuxiliaryFactory(self):
        return _materials.IsotropicHeat_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.IsotropicHeat_addAuxiliarySubfields(self)

# Register IsotropicHeat in _materials:
_materials.IsotropicHeat_swigregister(IsotropicHeat)
class Thermoelasticity(Material):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.Thermoelasticity_swiginit(self, _materials.new_Thermoelasticity())
    __swig_destroy__ = _materials.delete_Thermoelasticity

    def deallocate(self):
        return _materials.Thermoelasticity_deallocate(self)

    def useBodyForce(self, *args):
        return _materials.Thermoelasticity_useBodyForce(self, *args)

    def useHeatSource(self, *args):
        return _materials.Thermoelasticity_useHeatSource(self, *args)

    def setBulkRheology(self, rheology):
        return _materials.Thermoelasticity_setBulkRheology(self, rheology)

    def getBulkRheology(self):
        return _materials.Thermoelasticity_getBulkRheology(self)

    def verifyConfiguration(self, solution):
        return _materials.Thermoelasticity_verifyConfiguration(self, solution)

    def createIntegrator(self, solution):
        return _materials.Thermoelasticity_createIntegrator(self, solution)

    def createAuxiliaryField(self, solution, domainMesh):
        return _materials.Thermoelasticity_createAuxiliaryField(self, solution, domainMesh)

    def createDerivedField(self, solution, domainMesh):
        return _materials.Thermoelasticity_createDerivedField(self, solution, domainMesh)

    def getSolverDefaults(self, isParallel, hasFault):
        return _materials.Thermoelasticity_getSolverDefaults(self, isParallel, hasFault)

# Register Thermoelasticity in _materials:
_materials.Thermoelasticity_swigregister(Thermoelasticity)
class RheologyThermoelasticity(PyreComponent):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _materials.delete_RheologyThermoelasticity

    def deallocate(self):
        return _materials.RheologyThermoelasticity_deallocate(self)

    def getAuxiliaryFactory(self):
        return _materials.RheologyThermoelasticity_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.RheologyThermoelasticity_addAuxiliarySubfields(self)

    def updateKernelConstants(self, kernelConstants, dt):
        return _materials.RheologyThermoelasticity_updateKernelConstants(self, kernelConstants, dt)

# Register RheologyThermoelasticity in _materials:
_materials.RheologyThermoelasticity_swigregister(RheologyThermoelasticity)
class IsotropicLinearThermoelasticity(RheologyThermoelasticity):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.IsotropicLinearThermoelasticity_swiginit(self, _materials.new_IsotropicLinearThermoelasticity())
    __swig_destroy__ = _materials.delete_IsotropicLinearThermoelasticity

    def deallocate(self):
        return _materials.IsotropicLinearThermoelasticity_deallocate(self)

    def useReferenceState(self, *args):
        return _materials.IsotropicLinearThermoelasticity_useReferenceState(self, *args)

    def getAuxiliaryFactory(self):
        return _materials.IsotropicLinearThermoelasticity_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.IsotropicLinearThermoelasticity_addAuxiliarySubfields(self)

# Register IsotropicLinearThermoelasticity in _materials:
_materials.IsotropicLinearThermoelasticity_swigregister(IsotropicLinearThermoelasticity)
class Thermoporoelasticity(Material):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.Thermoporoelasticity_swiginit(self, _materials.new_Thermoporoelasticity())
    __swig_destroy__ = _materials.delete_Thermoporoelasticity

    def deallocate(self):
        return _materials.Thermoporoelasticity_deallocate(self)

    def useBodyForce(self, *args):
        return _materials.Thermoporoelasticity_useBodyForce(self, *args)

    def useSourceDensity(self, *args):
        return _materials.Thermoporoelasticity_useSourceDensity(self, *args)

    def useHeatSource(self, *args):
        return _materials.Thermoporoelasticity_useHeatSource(self, *args)

    def useReferenceState(self, *args):
        return _materials.Thermoporoelasticity_useReferenceState(self, *args)

    def setBulkRheology(self, rheology):
        return _materials.Thermoporoelasticity_setBulkRheology(self, rheology)

    def getBulkRheology(self):
        return _materials.Thermoporoelasticity_getBulkRheology(self)

    def verifyConfiguration(self, solution):
        return _materials.Thermoporoelasticity_verifyConfiguration(self, solution)

    def createIntegrator(self, solution):
        return _materials.Thermoporoelasticity_createIntegrator(self, solution)

    def createAuxiliaryField(self, solution, domainMesh):
        return _materials.Thermoporoelasticity_createAuxiliaryField(self, solution, domainMesh)

    def createDerivedField(self, solution, domainMesh):
        return _materials.Thermoporoelasticity_createDerivedField(self, solution, domainMesh)

    def getSolverDefaults(self, isParallel, hasFault):
        return _materials.Thermoporoelasticity_getSolverDefaults(self, isParallel, hasFault)

# Register Thermoporoelasticity in _materials:
_materials.Thermoporoelasticity_swigregister(Thermoporoelasticity)
class RheologyThermoporoelasticity(PyreComponent):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _materials.delete_RheologyThermoporoelasticity

    def deallocate(self):
        return _materials.RheologyThermoporoelasticity_deallocate(self)

    def getAuxiliaryFactory(self):
        return _materials.RheologyThermoporoelasticity_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.RheologyThermoporoelasticity_addAuxiliarySubfields(self)

    def updateKernelConstants(self, kernelConstants, dt):
        return _materials.RheologyThermoporoelasticity_updateKernelConstants(self, kernelConstants, dt)

# Register RheologyThermoporoelasticity in _materials:
_materials.RheologyThermoporoelasticity_swigregister(RheologyThermoporoelasticity)
class IsotropicLinearThermoporoelasticity(RheologyThermoporoelasticity):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _materials.IsotropicLinearThermoporoelasticity_swiginit(self, _materials.new_IsotropicLinearThermoporoelasticity())
    __swig_destroy__ = _materials.delete_IsotropicLinearThermoporoelasticity

    def deallocate(self):
        return _materials.IsotropicLinearThermoporoelasticity_deallocate(self)

    def useReferenceState(self, *args):
        return _materials.IsotropicLinearThermoporoelasticity_useReferenceState(self, *args)

    def getAuxiliaryFactory(self):
        return _materials.IsotropicLinearThermoporoelasticity_getAuxiliaryFactory(self)

    def addAuxiliarySubfields(self):
        return _materials.IsotropicLinearThermoporoelasticity_addAuxiliarySubfields(self)

# Register IsotropicLinearThermoporoelasticity in _materials:
_materials.IsotropicLinearThermoporoelasticity_swigregister(IsotropicLinearThermoporoelasticity)

